<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>agimus_demos</name>
  <version>0.0.0</version>
  <description>A package to aggregate all packages in agimus_demos.</description>
  <maintainer email="maximilien.naveau@gmail.com">Maximilien Naveau</maintainer>
  <license>BSD</license>

  <!-- Common -->
  <exec_depend>agimus_demos_common</exec_depend>

  <!-- Kuka -->
  <exec_depend>agimus_demo_00_kuka_controller</exec_depend>
  <exec_depend>agimus_demo_01_lfc_alone_kuka</exec_depend>
  <exec_depend>agimus_demo_02_simple_pd_plus_kuka</exec_depend>
  <exec_depend>agimus_demo_03_mpc_dummy_traj_kuka</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
